# Generated by Django 5.2.8 on 2025-11-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('lastname', models.TextField()),
                ('patronymic', models.TextField(blank=True, null=True)),
                ('role', models.TextField(choices=[('USER', 'User'), ('ADMIN', 'Admin'), ('Staff', 'Staff')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.TextField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
