# Generated by Django 5.2.8 on 2025-11-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('event_photo', models.ImageField(blank=True, help_text='Загрузите фотографию книги', null=True, upload_to='events/photos/full/', verbose_name='Обложка книги')),
                ('event_thumbnail', models.ImageField(blank=True, help_text='Генерируемая превью книги', null=True, upload_to='events/photos/thumbnails/', verbose_name='Превью обложки')),
            ],
        ),
    ]
