# Generated by Django 5.2.8 on 2025-11-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_photo',
            field=models.ImageField(blank=True, help_text='Загрузите фотографию книги', null=True, upload_to='events/photos/full/', verbose_name='Обложка книги'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_thumbnail',
            field=models.ImageField(blank=True, help_text='Генерируемая превью книги', null=True, upload_to='events/photos/thumbnails/', verbose_name='Превью обложки'),
        ),
    ]
