# Generated by Django 5.2.8 on 2025-11-22 17:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_photo',
            field=models.ImageField(blank=True, help_text='Загрузите фотографию события', null=True, upload_to='events/photos/full/', verbose_name='Фото события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_thumbnail',
            field=models.ImageField(blank=True, help_text='Автоматически генерируемое превью', null=True, upload_to='events/photos/thumbnails/', verbose_name='Превью фото'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Рейтинг'),
        ),
    ]
