# Generated by Django 5.2.8 on 2025-11-22 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_options_remove_event_date_event_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('24h', '24 часа до события'), ('2h', '2 часа до события'), ('both', '24 часа и 2 часа'), ('none', 'Без напоминаний')], default='both', max_length=10, verbose_name='Тип напоминания')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('unsubscribed', 'Отписан'), ('expired', 'Истекла')], default='active', max_length=20, verbose_name='Статус')),
                ('reminder_24h_sent', models.BooleanField(default=False)),
                ('reminder_1h_sent', models.BooleanField(default=False)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='events.event', verbose_name='Событие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик')),
            ],
            options={
                'verbose_name': 'Подписка на событие',
                'verbose_name_plural': 'Подписки на события',
                'ordering': ['-subscribed_at'],
                'unique_together': {('user', 'event')},
            },
        ),
    ]
