# Generated by Django 5.2.8 on 2025-11-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsubscription',
            name='reminder_1h_sent',
            field=models.BooleanField(default=False, verbose_name='Напоминание за 2ч отправлено'),
        ),
        migrations.AlterField(
            model_name='eventsubscription',
            name='reminder_24h_sent',
            field=models.BooleanField(default=False, verbose_name='Напоминание за 24ч отправлено'),
        ),
    ]
