# Generated by Django 5.2.8 on 2025-11-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='carousel/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения слайда', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Слайд карусели',
                'verbose_name_plural': 'Слайды карусели',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
