# Generated by Django 5.2.8 on 2025-11-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('cover_photo', models.ImageField(blank=True, help_text='Загрузите фотографию книги', null=True, upload_to='covers/full/', verbose_name='Обложка книги')),
                ('cover_thumbnail', models.ImageField(blank=True, help_text='Генерируемая превью книги', null=True, upload_to='covers/thumbnails/', verbose_name='Превью обложки')),
            ],
        ),
    ]
