# Generated by Django 5.2.8 on 2025-11-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AddField(
            model_name='book',
            name='cover_photo',
            field=models.ImageField(blank=True, help_text='Загрузите фотографию книги', null=True, upload_to='covers/full/', verbose_name='Обложка книги'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_thumbnail',
            field=models.ImageField(blank=True, help_text='Генерируемая превью книги', null=True, upload_to='covers/thumbnails/', verbose_name='Превью обложки'),
        ),
    ]
