# Generated by Django 5.2.8 on 2025-11-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_description_bookcopy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
