# Generated by Django 5.2.8 on 2025-11-23 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_bookcopy_registered_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='bookcopy',
            options={'verbose_name': 'Экземпляр книги', 'verbose_name_plural': 'Экземпляры книг'},
        ),
    ]
