# Generated by Django 5.2.8 on 2025-11-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_author_alter_book_genre_alter_book_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
    ]
