# Generated by Django 5.2.8 on 2025-11-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='planned_return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
