# Generated by Django 5.2.8 on 2025-11-23 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_bookcopy_registered_at'),
        ('rentals', '0003_rental_planned_return_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='planned_return_date',
            new_name='expected_return_date',
        ),
        migrations.AlterField(
            model_name='rental',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookcopy'),
        ),
    ]
